sudo: required

services:
  - docker

before_install:
  - docker login -u="$DOCKER_NAME" -p="$DOCKER_PASSWORD" 

script:
  - docker build -t $DOCKER_REPO/${DOCKER_IMAGE}:${TRAVIS_BUILD_NUMBER} ${DOCKER_BUILDDIR}

after_success:
  - docker push $DOCKER_REPO/${DOCKER_IMAGE}:${TRAVIS_BUILD_NUMBER}